### ISSUE TITLE
Update to support MongoDB 3.X

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/mongodb-formula#5]
The formula is currently targeting version 2.6 and we would like to upgrade to version 3.X (probably 3.4).

- [ ] Update the default package repository settings in the map.jinja
- [ ] Ensure that the initialization of the replica set is still following the proper steps for the new version

**Comment by shaidar** [comment]
Issued addressed [PR#6](https://github.com/mitodl/mongodb-formula/pull/6)
